"""
MIIE v1.6 Observation Provider Framework.

Provides the core infrastructure for observation providers including:
- Typed interfaces (contracts)
- Provider context and capabilities
- Registry with deterministic selection
- Lifecycle management
- Validation engine
- Health monitoring

No provider implementations are included — those belong to PR-11.
"""

from miie.providers.base import BaseGitProvider, BaseObservationProvider, ProviderMixin
from miie.providers.capabilities import (
    CapabilityCompatibility,
    CapabilityDiscovery,
    CapabilityNegotiator,
    CapabilityType,
    MetricSupport,
    ProviderCapabilities,
    ProviderStateInfo,
    ProviderVersion,
    SupportedSources,
)
from miie.providers.context import (
    CAPABILITY_API_REQUIRED,
    CAPABILITY_BATCH,
    CAPABILITY_GIT_NATIVE,
    CAPABILITY_LOCAL_ONLY,
    CAPABILITY_REAL_TIME,
    CAPABILITY_REMOTE_ONLY,
    METRIC_BOUNDS,
    METRIC_ID_M01,
    METRIC_ID_M02,
    METRIC_ID_M03,
    METRIC_ID_M04,
    METRIC_ID_M05,
    METRIC_ID_M06,
    METRIC_ID_M07,
    VALID_METRIC_IDS,
    VALID_QUALITY_TRANSITIONS,
    ExtractionPhase,
    ExtractionResult,
    HealthStatus,
    MetricBounds,
    ObservationMetrics,
    ObservationState,
    PriorityLevel,
    ProviderCapability,
    ProviderContext,
    ProviderEntry,
    ProviderErrorContext,
    ProviderFactoryResult,
    ProviderHealth,
    ProviderRegistrationConfig,
    ProviderState,
    QualityState,
    QualityStateTransition,
    ValidationResult,
)
from miie.providers.exceptions import (
    AuthenticationError,
    ConfigurationError,
    ConnectionError,
    DataFormatError,
    DependencyViolationError,
    DiscoveryError,
    DuplicateProviderError,
    ExtractionError,
    ExtractionTimeoutError,
    FreshnessViolationError,
    IncompatibleProviderError,
    ObservationError,
    PartialExtractionError,
    PipelineConsolidationError,
    PipelineError,
    PipelineStageError,
    PipelineTimeoutError,
    ProviderDisposedError,
    ProviderError,
    ProviderExtractionError,
    ProviderNotFoundError,
    ProviderNotInitializedError,
    ProviderNotReadyError,
    ProviderPausedError,
    RangeViolationError,
    RateLimitError,
    RegistrationError,
    RegistryError,
    SchemaViolationError,
    TimeoutError,
    ValidationError,
    create_extraction_error,
    create_provider_error,
)
from miie.providers.git import PROVIDER_ID as GIT_PROVIDER_ID
from miie.providers.git import (
    GitObservationProvider,
    git_provider_capabilities,
)
from miie.providers.github import (
    GITHUB_PR_PROVIDER_ID,
    GitHubAPIError,
    GitHubAuth,
    GitHubClient,
    GitHubProviderHealth,
    GitHubProviderValidator,
    GitHubPullRequestProvider,
    github_pr_provider_capabilities,
)
from miie.providers.health import (
    Availability,
    CapabilityCoverage,
    ErrorHistory,
    ErrorRecord,
    ExecutionMetrics,
    LastExecution,
    LatencyTracker,
    ProviderHealthMonitor,
)
from miie.providers.lifecycle import (
    LifecycleState,
    LifecycleTransition,
    ProviderLifecycleAudit,
    ProviderLifecycleManager,
)
from miie.providers.metadata import (
    ProviderMetadata,
    RegistryMetadata,
    create_git_provider_metadata,
    create_metadata_summary,
)
from miie.providers.orchestrator import (
    ExecutionPlan,
    MergeConflict,
    ObservationOrchestrator,
    OrchestratorConfig,
    OrchestratorDiagnostics,
    ProviderExecutionResult,
    ProviderTask,
)
from miie.providers.registry import (
    DeterministicRegistry,
    ObservationProviderRegistry,
)
from miie.providers.repository import (
    REPO_METADATA_PROVIDER_ID,
    RepositoryMetadata,
    RepositoryMetadataProvider,
    RepositoryProviderHealth,
    RepositoryProviderValidator,
    normalize_forks_count,
    normalize_last_push_latency,
    normalize_last_update_latency,
    normalize_open_issues_count,
    normalize_stars_count,
    normalize_watchers_count,
    repository_metadata_provider_capabilities,
)
from miie.providers.validation import (
    CompositeValidationRule,
    ConfidenceValidationRule,
    DependencyValidationRule,
    FreshnessValidationRule,
    ObservationValidationEngine,
    RangeValidationRule,
    RecoverySuggestion,
    SchemaValidationRule,
    ValidationRule,
)

__all__ = [
    # Contracts
    "IObservationProvider",
    "IGitProvider",
    "IObservationValidator",
    "IObservationTransformer",
    "IProviderHealthReporter",
    "IProviderRegistry",
    "IProviderFactory",
    "GitObservationProvider",
    "CommitObservationProvider",
    # Context
    "ProviderContext",
    "ProviderCapability",
    "ProviderHealth",
    "ProviderEntry",
    "ExtractionResult",
    "ValidationResult",
    "ObservationMetrics",
    "ProviderErrorContext",
    "ProviderRegistrationConfig",
    "ProviderFactoryResult",
    "MetricBounds",
    "QualityStateTransition",
    # Enums
    "ProviderState",
    "QualityState",
    "ObservationState",
    "PriorityLevel",
    "HealthStatus",
    "ExtractionPhase",
    # Constants
    "VALID_METRIC_IDS",
    "METRIC_BOUNDS",
    "VALID_QUALITY_TRANSITIONS",
    "CAPABILITY_GIT_NATIVE",
    "CAPABILITY_API_REQUIRED",
    "CAPABILITY_LOCAL_ONLY",
    "CAPABILITY_REMOTE_ONLY",
    "CAPABILITY_REAL_TIME",
    "CAPABILITY_BATCH",
    "METRIC_ID_M01",
    "METRIC_ID_M02",
    "METRIC_ID_M03",
    "METRIC_ID_M04",
    "METRIC_ID_M05",
    "METRIC_ID_M06",
    "METRIC_ID_M07",
    # Exceptions
    "ObservationError",
    "ProviderError",
    "ConnectionError",
    "AuthenticationError",
    "TimeoutError",
    "RateLimitError",
    "DataFormatError",
    "ProviderNotInitializedError",
    "ProviderDisposedError",
    "ProviderPausedError",
    "ExtractionError",
    "ProviderNotReadyError",
    "IncompatibleProviderError",
    "PartialExtractionError",
    "ExtractionTimeoutError",
    "ProviderExtractionError",
    "ValidationError",
    "SchemaViolationError",
    "RangeViolationError",
    "FreshnessViolationError",
    "DependencyViolationError",
    "RegistryError",
    "RegistrationError",
    "DiscoveryError",
    "ProviderNotFoundError",
    "DuplicateProviderError",
    "ConfigurationError",
    "PipelineError",
    "PipelineStageError",
    "PipelineTimeoutError",
    "PipelineConsolidationError",
    "create_provider_error",
    "create_extraction_error",
    # Capabilities
    "CapabilityType",
    "MetricSupport",
    "ProviderVersion",
    "SupportedSources",
    "ProviderStateInfo",
    "ProviderCapabilities",
    "CapabilityNegotiator",
    "CapabilityDiscovery",
    "CapabilityCompatibility",
    # Registry
    "ObservationProviderRegistry",
    "DeterministicRegistry",
    # Orchestrator
    "ObservationOrchestrator",
    "ExecutionPlan",
    "ProviderTask",
    "ProviderExecutionResult",
    "MergeConflict",
    "OrchestratorDiagnostics",
    "OrchestratorConfig",
    # Lifecycle
    "LifecycleState",
    "LifecycleTransition",
    "ProviderLifecycleManager",
    "ProviderLifecycleAudit",
    # Health
    "ExecutionMetrics",
    "LastExecution",
    "Availability",
    "ErrorRecord",
    "ErrorHistory",
    "LatencyTracker",
    "CapabilityCoverage",
    "ProviderHealthMonitor",
    # Validation
    "ObservationValidationEngine",
    "ValidationRule",
    "SchemaValidationRule",
    "RangeValidationRule",
    "ConfidenceValidationRule",
    "FreshnessValidationRule",
    "DependencyValidationRule",
    "CompositeValidationRule",
    "RecoverySuggestion",
    # Metadata
    "ProviderMetadata",
    "RegistryMetadata",
    "create_git_provider_metadata",
    "create_metadata_summary",
    # Base
    "BaseObservationProvider",
    "BaseGitProvider",
    "ProviderMixin",
    # Git Provider
    "GitObservationProvider",
    "GIT_PROVIDER_ID",
    "git_provider_capabilities",
    # GitHub PR Provider
    "GitHubPullRequestProvider",
    "GITHUB_PR_PROVIDER_ID",
    "github_pr_provider_capabilities",
    "GitHubClient",
    "GitHubAPIError",
    "GitHubAuth",
    "GitHubProviderHealth",
    "GitHubProviderValidator",
    # Repository Metadata Provider
    "RepositoryMetadataProvider",
    "REPO_METADATA_PROVIDER_ID",
    "repository_metadata_provider_capabilities",
    "RepositoryMetadata",
    "RepositoryProviderHealth",
    "RepositoryProviderValidator",
    "normalize_stars_count",
    "normalize_forks_count",
    "normalize_watchers_count",
    "normalize_open_issues_count",
    "normalize_last_push_latency",
    "normalize_last_update_latency",
]
