"""Output formatting for MIIE CLI.

Supports terminal summary, markdown report, JSON, CSV, and HTML output.
"""

from __future__ import annotations

import csv
import html
import io
import json
from datetime import datetime
from pathlib import Path
from typing import Any


# ── Markdown Report ────────────────────────────────────────────────────
def generate_markdown_report(
    repo_name: str,
    integrity_score: float,
    confidence_score: float,
    detector_outputs: dict[str, Any],
    metric_names: list[str],
    window_count: int,
    total_commits: Any,
    contributor_count: Any,
    timings: dict[str, float] | None = None,
) -> str:
    """Generate a markdown report."""
    lines = [
        "# MIIE Analysis Report",
        "",
        f"**Repository:** {repo_name}",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Scores",
        "",
        "| Score | Value | Rating |",
        "|-------|-------|--------|",
        f"| Integrity | {integrity_score:.3f} | {_score_label(integrity_score)} |",
        f"| Confidence | {confidence_score:.3f} | {_score_label(confidence_score)} |",
        "",
        "## Analysis Coverage",
        "",
        f"- **Commits:** {total_commits}",
        f"- **Contributors:** {contributor_count}",
        f"- **Windows:** {window_count}",
        f"- **Metrics:** {', '.join(metric_names)}",
        "",
        "## Detector Results",
        "",
        "| Detector | Name | Status |",
        "|----------|------|--------|",
    ]

    _det_names = {
        "D-01": "Distribution Drift",
        "D-02": "Correlation Breakdown",
        "D-03": "Threshold Compression",
    }

    for det_id in sorted(detector_outputs.keys()):
        det_data = detector_outputs[det_id]
        name = _det_names.get(det_id, det_id)
        if not isinstance(det_data, dict) or det_data.get("status") in ("error", "skipped"):
            status = "⚠️ Error"
        elif (
            det_data.get("drift_detected")
            or det_data.get("breakdown_detected")
            or det_data.get("compression_detected", False)
        ):
            status = "🔴 Detected"
        else:
            status = "🟢 Clear"
        lines.append(f"| {det_id} | {name} | {status} |")

    if timings:
        lines.extend(
            [
                "",
                "## Performance",
                "",
                "| Stage | Time |",
                "|-------|------|",
            ]
        )
        for stage, elapsed in timings.items():
            lines.append(f"| {stage} | {elapsed:.2f}s |")
        lines.append(f"| **Total** | **{sum(timings.values()):.2f}s** |")

    lines.extend(
        [
            "",
            "---",
            f"*Generated by MIIE v{__import__('miie').__version__}*",
        ]
    )

    return "\n".join(lines)


# ── CSV Export ─────────────────────────────────────────────────────────
def generate_csv_scores(
    repo_name: str,
    integrity_score: float,
    confidence_score: float,
    detector_outputs: dict[str, Any],
) -> str:
    """Generate CSV output for scores."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["repository", "integrity_score", "confidence_score", "detectors_triggered", "risk_level"])

    triggered = 0
    for det_data in detector_outputs.values():
        if isinstance(det_data, dict) and (
            det_data.get("drift_detected")
            or det_data.get("breakdown_detected")
            or det_data.get("compression_detected", False)
        ):
            triggered += 1

    if triggered == 0:
        risk = "Very Low"
    elif triggered == 1:
        risk = "Low"
    elif triggered == 2:
        risk = "Moderate"
    else:
        risk = "High"

    writer.writerow([repo_name, f"{integrity_score:.3f}", f"{confidence_score:.3f}", triggered, risk])
    return output.getvalue()


def generate_csv_metrics(
    metric_names: list[str],
    metric_values: dict[str, Any],
) -> str:
    """Generate CSV output for metrics."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["metric_id", "value", "status"])

    for metric_id in metric_names:
        value = metric_values.get(metric_id)
        if value is None:
            writer.writerow([metric_id, "", "unavailable"])
        else:
            writer.writerow([metric_id, f"{value:.4f}" if isinstance(value, float) else str(value), "available"])

    return output.getvalue()


# ── HTML Report ────────────────────────────────────────────────────────
def generate_html_report(
    repo_name: str,
    integrity_score: float,
    confidence_score: float,
    detector_outputs: dict[str, Any],
    metric_names: list[str],
    window_count: int,
) -> str:
    """Generate an HTML report."""
    repo_name_esc = html.escape(repo_name)
    integrity_color = _score_color(integrity_score)
    confidence_color = _score_color(confidence_score)

    _det_names = {
        "D-01": "Distribution Drift",
        "D-02": "Correlation Breakdown",
        "D-03": "Threshold Compression",
    }

    detector_rows = ""
    for det_id in sorted(detector_outputs.keys()):
        det_data = detector_outputs[det_id]
        name = _det_names.get(det_id, det_id)
        if not isinstance(det_data, dict) or det_data.get("status") in ("error", "skipped"):
            status_html = '<span style="color:#f39c12">⚠ Error</span>'
        elif (
            det_data.get("drift_detected")
            or det_data.get("breakdown_detected")
            or det_data.get("compression_detected", False)
        ):
            status_html = '<span style="color:#e74c3c">🔴 Detected</span>'
        else:
            status_html = '<span style="color:#27ae60">🟢 Clear</span>'
        detector_rows += f"<tr><td>{html.escape(det_id)}</td><td>{html.escape(name)}</td><td>{status_html}</td></tr>\n"

    return f"""<!DOCTYPE html>
<html>
<head>
    <title>MIIE Report — {repo_name_esc}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }}
        h1 {{ color: #2c3e50; }}
        .score {{ display: inline-block; padding: 10px 20px; border-radius: 8px; margin: 5px; }}
        .score-value {{ font-size: 24px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #f8f9fa; }}
    </style>
</head>
<body>
    <h1>MIIE Analysis Report</h1>
    <p><strong>Repository:</strong> {repo_name_esc}</p>
    <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

    <h2>Scores</h2>
    <div class="score" style="background:{integrity_color}20;border:2px solid {integrity_color}">
        <div class="score-value" style="color:{integrity_color}">{integrity_score:.3f}</div>
        <div>Integrity Score ({_score_label(integrity_score)})</div>
    </div>
    <div class="score" style="background:{confidence_color}20;border:2px solid {confidence_color}">
        <div class="score-value" style="color:{confidence_color}">{confidence_score:.3f}</div>
        <div>Confidence Score ({_score_label(confidence_score)})</div>
    </div>

    <h2>Detector Results</h2>
    <table>
        <tr><th>ID</th><th>Name</th><th>Status</th></tr>
        {detector_rows}
    </table>

    <h2>Analysis Coverage</h2>
    <ul>
        <li><strong>Metric Count:</strong> {len(metric_names)}</li>
        <li><strong>Windows:</strong> {window_count}</li>
    </ul>

    <hr>
    <p><em>Generated by MIIE v{__import__('miie').__version__}</em></p>
</body>
</html>"""


# ── Report Writer ──────────────────────────────────────────────────────
def write_reports(
    output_dir: str,
    formats: list[str],
    repo_name: str,
    integrity_score: float,
    confidence_score: float,
    detector_outputs: dict[str, Any],
    metric_names: list[str],
    window_count: int,
    total_commits: Any,
    contributor_count: Any,
    timings: dict[str, float] | None = None,
    json_data: dict | None = None,
) -> dict[str, Path]:
    """Write reports in the specified formats."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = {}

    for fmt in formats:
        if fmt == "md":
            content = generate_markdown_report(
                repo_name,
                integrity_score,
                confidence_score,
                detector_outputs,
                metric_names,
                window_count,
                total_commits,
                contributor_count,
                timings,
            )
            path = out / "report.md"
            path.write_text(content, encoding="utf-8")
            paths["md"] = path

        elif fmt == "csv":
            content = generate_csv_scores(
                repo_name,
                integrity_score,
                confidence_score,
                detector_outputs,
            )
            path = out / "scores.csv"
            path.write_text(content, encoding="utf-8")
            paths["csv"] = path

        elif fmt == "html":
            content = generate_html_report(
                repo_name,
                integrity_score,
                confidence_score,
                detector_outputs,
                metric_names,
                window_count,
            )
            path = out / "report.html"
            path.write_text(content, encoding="utf-8")
            paths["html"] = path

        elif fmt == "json" and json_data:
            path = out / "report.json"
            path.write_text(json.dumps(json_data, indent=2, default=str), encoding="utf-8")
            paths["json"] = path

    return paths


# ── Helpers ────────────────────────────────────────────────────────────
def _score_label(value: float) -> str:
    if value >= 0.9:
        return "Very High"
    elif value >= 0.7:
        return "High"
    elif value >= 0.5:
        return "Moderate"
    else:
        return "Low"


def _score_color(value: float) -> str:
    if value >= 0.9:
        return "#27ae60"
    elif value >= 0.7:
        return "#3498db"
    elif value >= 0.5:
        return "#f39c12"
    else:
        return "#e74c3c"
